name: Continuous Delivery
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: deploy
        run: |
          npm install @google/clasp
          clasp login --creds <(echo "${{ secrets.CREDS }}")
          clasp deploy --description "Library to log output."
