name: Continuous Integration
on:
  pull_request:
    branches: [ master ]

jobs:
  js-lint:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: |
          npm install
          npx eslint *.js
  
  markdown-lint:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: |
          npm install -g markdownlint-cli
          markdownlint *.md
