name: Continuous Integration
on:
  pull_request:
    branches: [ dev, master ]

env:
  TOOLS: ci-helpers

jobs:
  check-mergeability:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: |
          bash $TOOLS/check-branch-mergeability.sh

  check-tag-existence:
    runs-on: ubuntu-20.04
    needs: check-mergeability
    if: github.base_ref == 'master'

    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: |
          bash check-tag-existence.sh

  js-lint:
    runs-on: ubuntu-20.04
    needs: check-mergeability
    if: github.base_ref == 'dev'
    
    strategy:
      matrix:
        node: [12, 14, 16]
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      - name: lint
        run: |
          npm install
          npx eslint *.js
  
  markdown-lint:
    runs-on: ubuntu-20.04
    needs: check-mergeability
    if: github.base_ref == 'dev'
    
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: |
          npm install -g markdownlint-cli
          markdownlint *.md

  shell-lint:
    runs-on: ubuntu-20.04
    needs: check-mergeability
    if: github.base_ref == 'dev'
    
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: |
          shellcheck tools/*.sh
