name: Continuous Integration
on:
  pull_request:
    branches: [ dev ]

env:
  TOOLS: tools

jobs:
  check-target:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: |
          bash $TOOLS/check-branch-mergeability.sh

  js-lint:
    runs-on: ubuntu-20.04
    needs: check-target
    
    strategy:
      matrix:
        node: [12, 14, 16]
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      - name: lint
        run: |
          npm install
          npx eslint *.js
  
  markdown-lint:
    runs-on: ubuntu-20.04
    needs: check-target
    
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: |
          npm install -g markdownlint-cli
          markdownlint *.md
